# Generated by Django 4.1.5 on 2024-02-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('To Do', 'TODO'), ('In Progress', 'IN_PROGRESS'), ('Done', 'DONE')], default='To Do', max_length=20)),
                ('due_date', models.DateField()),
            ],
        ),
    ]
